# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SF7wR6TraS52rRNUOvqkeljgVDJIzwT0
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #charts
import seaborn as sns

df = pd.read_csv('Churn_Modelling.csv')
df.head()
df['NumOfProducts'].unique()
plt.bar(df['Gender'],df['Tenure'])

sns.countplot(df['Gender'])

sns.boxplot(df['Tenure'])

#univariate analysis
plt.plot(df['Balance'],np.zeros_like(df['Balance']),'o')

#bivariate analysis

sns.FacetGrid(df,hue="Gender",size=5).map(plt.scatter,"Gender","Balance").add_legend()
plt.show()

sns.pairplot(df, hue="Gender", height=2)

#descriptive analysis
print(df.describe())

#Handle the Missing values
df.isnull().sum()

#Find the outliers and replace the outliers
df['Balance'].median(),df['Age'].mean()
df['Balance']=df['Balance'].fillna(df['Balance'].median())
df

#Check for Categorical columns and perform encoding
obj_df = df.select_dtypes(include=['object']).copy()
obj_df
from sklearn.preprocessing import LabelEncoder
from collections import Counter as count
le=LabelEncoder()
count(df['Geography'])

df['Exited']=df['Exited'].replace([1,0],('Yes','No'))
df

df['Geography']=le.fit_transform(df['Geography'])

df1=pd.read_csv('/content/Churn_Modelling.csv')
df1['Geography']

country=pd.get_dummies(df['Geography'])
country

#Split the data into dependent and independent variables
x=df.iloc[:,0:3]
y=df['HasCrCard']
x

y

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.6,random_state=11)

xtrain

xtest

ytrain

ytest